### ISSUE TITLE
Mouse Focus Between Buttons

### ISSUE THREAD

**Issue by Crumdidlyumshis** [ElvUI-WotLK/ElvUI_MicrobarEnhancement#1]
https://www.youtube.com/watch?v=7TdJHNXX_gs

**Comment by Bunny67** [comment]
spacing ~20 on blizzard button
We obtain the same

**Comment by Crumdidlyumshis** [comment]
But if I hover my mouse over the spacing while fading, it will fade all. 

Shouldn't it stay focused when hovering all of the buttons?

Но если я завишу моя мышь над дистанционированием пока увядающ, то он увянет все. Не должен он остаться сфокусированным завиша все кнопки?

**Comment by Bunny67** [comment]
https://github.com/ElvUI/ElvUI_Microbar/commit/278d85b978533eb85978f16ea6b2f9ecdcfc1dba ?

**Comment by Crumdidlyumshis** [comment]
Thank you! That fixed it
